# Generated by Django 3.0.5 on 2020-04-12 12:40

from django.db import migrations, models
import django.db.models.deletion
import maingame.utils.db_defaults


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('question', models.TextField()),
                ('outcome', models.TextField()),
                ('stakes', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('multiplier', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='BetOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maingame.Bet')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StatusType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('join_date', models.DateTimeField()),
                ('email', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserGroupRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maingame.Group')),
                ('role', models.ForeignKey(default=maingame.utils.db_defaults.set_default_role, on_delete=django.db.models.deletion.SET_DEFAULT, to='maingame.UserRole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maingame.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserEventRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maingame.Event')),
                ('role', models.ForeignKey(default=maingame.utils.db_defaults.set_default_role, on_delete=django.db.models.deletion.SET_DEFAULT, to='maingame.UserRole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maingame.User')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('rank', models.IntegerField()),
                ('bet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maingame.Bet')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maingame.Event')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maingame.User')),
            ],
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_option', models.CharField(blank=True, max_length=200)),
                ('bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maingame.Bet')),
                ('option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maingame.BetOption')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maingame.User')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='players',
            field=models.ManyToManyField(to='maingame.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='groups',
            field=models.ManyToManyField(to='maingame.Group'),
        ),
        migrations.AddField(
            model_name='event',
            name='players',
            field=models.ManyToManyField(to='maingame.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maingame.EventType'),
        ),
        migrations.AddField(
            model_name='bet',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maingame.User'),
        ),
        migrations.AddField(
            model_name='bet',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maingame.Event'),
        ),
        migrations.AddField(
            model_name='bet',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maingame.StatusType'),
        ),
    ]
