# Generated by Django 3.0.5 on 2020-04-24 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maingame', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='betresult',
            unique_together={('player', 'bet')},
        ),
        migrations.AlterUniqueTogether(
            name='eventresult',
            unique_together={('player', 'event')},
        ),
        migrations.AlterUniqueTogether(
            name='placement',
            unique_together={('player', 'bet')},
        ),
        migrations.AlterUniqueTogether(
            name='usereventrole',
            unique_together={('user', 'event')},
        ),
        migrations.AlterUniqueTogether(
            name='usergrouprole',
            unique_together={('user', 'group')},
        ),
        migrations.AddField(
            model_name='event',
            name='current_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maingame.EventStage'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='stages',
            field=models.ManyToManyField(to='maingame.EventStage'),
        ),
    ]
