# Generated by Django 3.0.5 on 2020-04-08 02:50

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import maingame.utils.db_defaults


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField()),
                ('question', models.TextField()),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, null=True, size=None)),
                ('outcome', models.TextField()),
                ('on_the_line', models.TextField()),
                ('notes', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('multiplier', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StatusType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('join_date', models.DateTimeField()),
                ('email', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserGroupRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maingame.Group')),
                ('role', models.ForeignKey(default=maingame.utils.db_defaults.set_default_role, on_delete=django.db.models.deletion.SET_DEFAULT, to='maingame.UserRoles')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maingame.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserEventRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maingame.Event')),
                ('role', models.ForeignKey(default=maingame.utils.db_defaults.set_default_role, on_delete=django.db.models.deletion.SET_DEFAULT, to='maingame.UserRoles')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maingame.User')),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('rank', models.IntegerField()),
                ('bet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maingame.Bet')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maingame.Event')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maingame.User')),
            ],
        ),
        migrations.CreateModel(
            name='Placements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200)),
                ('bet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maingame.Bet')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maingame.User')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='players',
            field=models.ManyToManyField(to='maingame.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='groups',
            field=models.ManyToManyField(to='maingame.Group'),
        ),
        migrations.AddField(
            model_name='event',
            name='players',
            field=models.ManyToManyField(to='maingame.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maingame.EventType'),
        ),
        migrations.AddField(
            model_name='bet',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maingame.Event'),
        ),
        migrations.AddField(
            model_name='bet',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maingame.StatusType'),
        ),
    ]
